net_depth = 50  # resnet depth, default is 50
epoch = 100000  # epoch to train the network
batch_size = 128  # batch size to train network
lr_steps = [40000, 60000, 80000]  # learning rate to train network
momentum = 0.9  # learning alg momentum
weight_deacy = 5e-4  # learning alg momentum
eval_datasets = ['lfw', 'cplfw', 'agedb_30']  # evluation datasets
eval_db_path = '../ver_data'  # evluate datasets base path
image_size = (112, 112)  # the image size
num_output = 85164  # the image size
tfrecords_file_path = '../train_data'  # path to the output of tfrecords file path
premodel_path = '/Users/finup/Desktop/rg/face_rg_files/premodels/pm_insight_auroua/1030_auroua_out/mgpu_res/ckpt/InsightFace_iter_500000.ckpt'
saver_maxkeep = 100  # tf.train.Saver max keep ckpt files
buffer_size = 100000  # tf dataset api buffer size  # MGPU 变大*10
log_device_mapping = False  # show device placement log  # MGPU 删掉了log_file_path参数
summary_interval = 500  # interval to save summary
ckpt_interval = 5000  # intervals to save ckpt file  # MGPU 变小/2
validate_interval = 5000  # intervals to save ckpt file
show_info_interval = 10  # intervals to show information
# num_gpus = [0, 1]  # the num of gpus')  # MGPU
num_gpus = [0]  # the num of gpus')  # MGPU
tower_name = 'tower'  # tower name')  # MGPU
